import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Now reacted taxes',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link className='headerLink' href='./'>Home</Link>
          <Link className='headerLink' href='./calculator'>Calculator</Link>
          <Link  className='headerLink' href='./info'>Info</Link>
          <Link  className='headerLink' href='./about'>About</Link>
        </header>

        {children}
      </body>
    </html>
  )
}
