import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/UI/header/Header'

const inter = Inter({ subsets: ['cyrillic'] })

export const metadata = {
  title: 'Now reacted taxes',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
